/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/ActionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Transaction: typeof import('./src/components/Transaction.vue')['default']
    TransactionModal: typeof import('./src/components/TransactionModal.vue')['default']
    TransactionReceipt: typeof import('./src/components/TransactionReceipt.vue')['default']
  }
}
