/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { InitialVoiceCreditProxy } from "../InitialVoiceCreditProxy";

export class InitialVoiceCreditProxy__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InitialVoiceCreditProxy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InitialVoiceCreditProxy;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "getVoiceCredits",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
