/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IUserRegistry } from "../IUserRegistry";

export class IUserRegistry__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUserRegistry {
    return new Contract(address, _abi, signerOrProvider) as IUserRegistry;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "isVerifiedUser",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
